let processDev = {
  title: 'npm',
    version: 'v8.11.1',
    moduleLoadList:
     [ 'Binding contextify',
    'Binding natives',
    'Binding config',
    'NativeModule events',
    'Binding async_wrap',
    'Binding icu',
    'NativeModule util',
    'NativeModule internal/errors',
    'NativeModule internal/encoding',
    'NativeModule internal/util',
    'Binding util',
    'Binding constants',
    'NativeModule internal/util/types',
    'Binding buffer',
    'NativeModule buffer',
    'NativeModule internal/buffer',
    'Binding uv',
    'NativeModule internal/process',
    'NativeModule internal/process/warning',
    'NativeModule internal/process/next_tick',
    'NativeModule internal/async_hooks',
    'NativeModule internal/process/promises',
    'NativeModule internal/process/stdio',
    'Binding performance',
    'NativeModule perf_hooks',
    'NativeModule internal/linkedlist',
    'NativeModule internal/trace_events_async_hooks',
    'Binding trace_events',
    'NativeModule async_hooks',
    'NativeModule internal/inspector_async_hook',
    'Binding inspector',
    'NativeModule timers',
    'Binding timer_wrap',
    'NativeModule assert',
    'NativeModule module',
    'NativeModule internal/module',
    'NativeModule internal/url',
    'NativeModule internal/querystring',
    'NativeModule querystring',
    'Binding url',
    'NativeModule vm',
    'NativeModule fs',
    'NativeModule path',
    'Binding fs',
    'NativeModule stream',
    'NativeModule internal/streams/legacy',
    'NativeModule _stream_readable',
    'NativeModule internal/streams/BufferList',
    'NativeModule internal/streams/destroy',
    'NativeModule _stream_writable',
    'NativeModule _stream_duplex',
    'NativeModule _stream_transform',
    'NativeModule _stream_passthrough',
    'Binding fs_event_wrap',
    'NativeModule internal/fs',
    'NativeModule internal/loader/Loader',
    'NativeModule internal/loader/ModuleWrap',
    'Internal Binding module_wrap',
    'NativeModule internal/loader/ModuleMap',
    'NativeModule internal/loader/ModuleJob',
    'NativeModule internal/safe_globals',
    'NativeModule internal/loader/ModuleRequest',
    'NativeModule url',
    'NativeModule internal/loader/search',
    'NativeModule console',
    'Binding tty_wrap',
    'NativeModule tty',
    'NativeModule net',
    'NativeModule internal/net',
    'Binding cares_wrap',
    'Binding tcp_wrap',
    'Binding pipe_wrap',
    'Binding stream_wrap',
    'NativeModule dns',
    'NativeModule readline',
    'NativeModule string_decoder',
    'NativeModule internal/readline',
    'Binding signal_wrap',
    'NativeModule crypto',
    'Binding crypto',
    'NativeModule internal/streams/lazy_transform',
    'NativeModule constants',
    'NativeModule http',
    'NativeModule _http_agent',
    'NativeModule _http_client',
    'Binding http_parser',
    'NativeModule _http_common',
    'NativeModule internal/freelist',
    'NativeModule internal/http',
    'NativeModule _http_incoming',
    'NativeModule _http_outgoing',
    'NativeModule _http_server',
    'NativeModule os',
    'NativeModule internal/os',
    'Binding os',
    'NativeModule zlib',
    'Binding zlib',
    'NativeModule https',
    'NativeModule tls',
    'NativeModule _tls_common',
    ... 13 more items ],
    versions:
   { http_parser: '2.8.0',
    node: '8.11.1',
    v8: '6.2.414.50',
    uv: '1.19.1',
    zlib: '1.2.11',
    ares: '1.10.1-DEV',
    modules: '57',
    nghttp2: '1.25.0',
    openssl: '1.0.2o',
    icu: '60.1',
    unicode: '10.0',
    cldr: '32.0',
    tz: '2017c' },
  arch: 'x64',
    platform: 'win32',
    release:
  { name: 'node',
    lts: 'Carbon',
    sourceUrl: 'https://nodejs.org/download/release/v8.11.1/node-v8.11.1.tar.gz',
    headersUrl: 'https://nodejs.org/download/release/v8.11.1/node-v8.11.1-headers.tar.gz',
    libUrl: 'https://nodejs.org/download/release/v8.11.1/win-x64/node.lib' },
  argv:
    [ 'C:\\Program Files\\nodejs\\node.exe',
      'D:\\work\\react\\back-project\\scripts\\start.js' ],
  execArgv: [],
  env:
  { ALLUSERSPROFILE: 'C:\\ProgramData',
    APPDATA: 'C:\\Users\\Administrator\\AppData\\Roaming',
    BABEL_ENV: 'development',
    CommonProgramFiles: 'C:\\Program Files\\Common Files',
    'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
    CommonProgramW6432: 'C:\\Program Files\\Common Files',
    COMPUTERNAME: 'SD-201705071251',
    ComSpec: 'C:\\Windows\\system32\\cmd.exe',
    FP_NO_HOST_CHECK: 'NO',
    HOME: 'C:\\Users\\Administrator',
    HOMEDRIVE: 'C:',
    HOMEPATH: '\\Users\\Administrator',
    INIT_CWD: 'D:\\work\\react\\back-project',
    JAVA_HOME: 'C:\\Program Files\\Java\\jdk1.7.0_45',
    LOCALAPPDATA: 'C:\\Users\\Administrator\\AppData\\Local',
    LOGONSERVER: '\\\\SD-201705071251',
    MAVEN_HOME: 'E:\\devsoft\\apache-maven-3.3.9',
    MOZ_PLUGIN_PATH: 'C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\',
    NODE: 'C:\\Program Files\\nodejs\\node.exe',
    NODE_ENV: 'development',
    NODE_EXE: 'C:\\Program Files\\nodejs\\\\node.exe',
    NODE_PATH: '',
    NPM_CLI_JS: 'C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js',
    npm_config_access: '',
    npm_config_allow_same_version: '',
    npm_config_also: '',
    npm_config_always_auth: '',
    npm_config_argv: '{"remain":[],"cooked":["run","dev"],"original":["run","dev"]}',
    npm_config_auth_type: 'legacy',
    npm_config_bin_links: 'true',
    npm_config_browser: '',
    npm_config_ca: '',
    npm_config_cache: 'C:\\Users\\Administrator\\AppData\\Roaming\\npm-cache',
    npm_config_cache_lock_retries: '10',
    npm_config_cache_lock_stale: '60000',
    npm_config_cache_lock_wait: '10000',
    npm_config_cache_max: 'Infinity',
    npm_config_cache_min: '10',
    npm_config_cafile: '',
    npm_config_cert: '',
    npm_config_cidr: '',
    npm_config_color: 'true',
    npm_config_commit_hooks: 'true',
    npm_config_depth: 'Infinity',
    npm_config_description: 'true',
    npm_config_dev: '',
    npm_config_dry_run: '',
    npm_config_editor: 'notepad.exe',
    npm_config_engine_strict: '',
    npm_config_fetch_retries: '2',
    npm_config_fetch_retry_factor: '10',
    npm_config_fetch_retry_maxtimeout: '60000',
    npm_config_fetch_retry_mintimeout: '10000',
    npm_config_force: '',
    npm_config_git: 'git',
    npm_config_git_tag_version: 'true',
    npm_config_global: '',
    npm_config_globalconfig: 'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\etc\\npmrc',
    npm_config_globalignorefile: 'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\etc\\npmignore',
    npm_config_global_style: '',
    npm_config_group: '',
    npm_config_ham_it_up: '',
    npm_config_heading: 'npm',
    npm_config_https_proxy: '',
    npm_config_if_present: '',
    npm_config_ignore_prepublish: '',
    npm_config_ignore_scripts: '',
    npm_config_init_author_email: '',
    npm_config_init_author_name: '',
    npm_config_init_author_url: '',
    npm_config_init_license: 'ISC',
    npm_config_init_module: 'C:\\Users\\Administrator\\.npm-init.js',
    npm_config_init_version: '1.0.0',
    npm_config_json: '',
    npm_config_key: '',
    npm_config_legacy_bundling: '',
    npm_config_link: '',
    npm_config_local_address: '',
    npm_config_loglevel: 'notice',
    npm_config_logs_max: '10',
    npm_config_long: '',
    npm_config_maxsockets: '50',
    npm_config_message: '%s',
    npm_config_metrics_registry: 'https://registry.npmjs.org/',
    npm_config_node_gyp: 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
    npm_config_node_options: '',
    npm_config_node_version: '8.11.1',
    npm_config_offline: '',
    npm_config_onload_script: '',
    npm_config_only: '',
    npm_config_optional: 'true',
    npm_config_otp: '',
    npm_config_package_lock: 'true',
    npm_config_package_lock_only: '',
    npm_config_parseable: '',
    npm_config_prefer_offline: '',
    npm_config_prefer_online: '',
    npm_config_prefix: 'C:\\Users\\Administrator\\AppData\\Roaming\\npm',
    npm_config_production: '',
    npm_config_progress: 'true',
    npm_config_proxy: '',
    npm_config_read_only: '',
    npm_config_rebuild_bundle: 'true',
    npm_config_registry: 'https://registry.npmjs.org/',
    npm_config_rollback: 'true',
    npm_config_save: 'true',
    npm_config_save_bundle: '',
    npm_config_save_dev: '',
    npm_config_save_exact: '',
    npm_config_save_optional: '',
    npm_config_save_prefix: '^',
    npm_config_save_prod: '',
    npm_config_scope: '',
    npm_config_scripts_prepend_node_path: 'warn-only',
    npm_config_script_shell: '',
    npm_config_searchexclude: '',
    npm_config_searchlimit: '20',
    npm_config_searchopts: '',
    npm_config_searchstaleness: '900',
    npm_config_send_metrics: '',
    npm_config_shell: 'C:\\Windows\\system32\\cmd.exe',
    npm_config_shrinkwrap: 'true',
    npm_config_sign_git_tag: '',
    npm_config_sso_poll_frequency: '500',
    npm_config_sso_type: 'oauth',
    npm_config_strict_ssl: 'true',
    npm_config_tag: 'latest',
    npm_config_tag_version_prefix: 'v',
    npm_config_timing: '',
    npm_config_tmp: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
    npm_config_umask: '0000',
    npm_config_unicode: '',
    npm_config_unsafe_perm: 'true',
    npm_config_usage: '',
    npm_config_user: '',
    npm_config_userconfig: 'C:\\Users\\Administrator\\.npmrc',
    npm_config_user_agent: 'npm/5.6.0 node/v8.11.1 win32 x64',
    npm_config_version: '',
    npm_config_versions: '',
    npm_config_viewer: 'browser',
    npm_execpath: 'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    npm_lifecycle_event: 'dev',
    npm_lifecycle_script: 'node scripts/start.js',
    npm_node_execpath: 'C:\\Program Files\\nodejs\\node.exe',
    npm_package_babel_presets_0: 'react-app',
    npm_package_dependencies_autoprefixer: '7.1.6',
    npm_package_dependencies_babel_core: '6.26.0',
    npm_package_dependencies_babel_eslint: '7.2.3',
    npm_package_dependencies_babel_jest: '20.0.3',
    npm_package_dependencies_babel_loader: '7.1.2',
    npm_package_dependencies_babel_preset_react_app: '^3.1.2',
    npm_package_dependencies_babel_runtime: '6.26.0',
    npm_package_dependencies_case_sensitive_paths_webpack_plugin: '2.1.1',
    npm_package_dependencies_chalk: '1.1.3',
    npm_package_dependencies_css_loader: '0.28.7',
    npm_package_dependencies_dotenv: '4.0.0',
    npm_package_dependencies_dotenv_expand: '4.2.0',
    npm_package_dependencies_eslint: '4.10.0',
    npm_package_dependencies_eslint_config_react_app: '^2.1.0',
    npm_package_dependencies_eslint_loader: '1.9.0',
    npm_package_dependencies_eslint_plugin_flowtype: '2.39.1',
    npm_package_dependencies_eslint_plugin_import: '2.8.0',
    npm_package_dependencies_eslint_plugin_jsx_a11y: '5.1.1',
    npm_package_dependencies_eslint_plugin_react: '7.4.0',
    npm_package_dependencies_extract_text_webpack_plugin: '3.0.2',
    npm_package_dependencies_file_loader: '1.1.5',
    npm_package_dependencies_fs_extra: '3.0.1',
    npm_package_dependencies_html_webpack_plugin: '2.29.0',
    npm_package_dependencies_jest: '20.0.4',
    npm_package_dependencies_object_assign: '4.1.1',
    npm_package_dependencies_postcss_flexbugs_fixes: '3.2.0',
    npm_package_dependencies_postcss_loader: '2.0.8',
    npm_package_dependencies_promise: '8.0.1',
    npm_package_dependencies_raf: '3.4.0',
    npm_package_dependencies_react: '^16.5.1',
    npm_package_dependencies_react_dev_utils: '^5.0.2',
    npm_package_dependencies_react_dom: '^16.5.1',
    npm_package_dependencies_resolve: '1.6.0',
    npm_package_dependencies_style_loader: '0.19.0',
    npm_package_dependencies_sw_precache_webpack_plugin: '0.11.4',
    npm_package_dependencies_url_loader: '0.6.2',
    npm_package_dependencies_webpack: '3.8.1',
    npm_package_dependencies_webpack_dev_server: '2.11.3',
    npm_package_dependencies_webpack_manifest_plugin: '1.3.2',
    npm_package_dependencies_whatwg_fetch: '2.0.3',
     npm_package_eslintConfig_extends: 'react-app',
     npm_package_jest_collectCoverageFrom_0: 'src/**/*.{js,jsx,mjs}',
     npm_package_jest_moduleFileExtensions_0: 'web.js',
     npm_package_jest_moduleFileExtensions_1: 'js',
     npm_package_jest_moduleFileExtensions_2: 'json',
     npm_package_jest_moduleFileExtensions_3: 'web.jsx',
     npm_package_jest_moduleFileExtensions_4: 'jsx',
     npm_package_jest_moduleFileExtensions_5: 'node',
     npm_package_jest_moduleFileExtensions_6: 'mjs',
     npm_package_jest_moduleNameMapper__react_native_: 'react-native-web',
     npm_package_jest_setupFiles_0: '<rootDir>/config/polyfills.js',
     npm_package_jest_testEnvironment: 'node',
     npm_package_jest_testMatch_0: '<rootDir>/src/**/__tests__/**/*.{js,jsx,mjs}',
     npm_package_jest_testMatch_1: '<rootDir>/src/**/?(*.)(spec|test).{js,jsx,mjs}',
     npm_package_jest_testURL: 'http://localhost',
     npm_package_jest_transformIgnorePatterns_0: '[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$',
     npm_package_jest_transform______css_: '<rootDir>/config/jest/cssTransform.js',
     npm_package_jest_transform_______js_jsx_mjs__: '<rootDir>/node_modules/babel-jest',
     npm_package_jest_transform__________js_jsx_mjs_css_json___: '<rootDir>/config/jest/fileTransform.js',
     npm_package_name: 'back-project',
     npm_package_private: 'true',
     npm_package_readmeFilename: 'README.md',
     npm_package_scripts_build: 'node scripts/build.js',
     npm_package_scripts_dev: 'node scripts/start.js',
     npm_package_scripts_start: 'npm run dev',
     npm_package_scripts_test: 'node scripts/test.js --env=jsdom',
     npm_package_version: '0.1.0',
     NPM_PREFIX_NPM_CLI_JS: 'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
     NUMBER_OF_PROCESSORS: '4',
     OS: 'Windows_NT',
     PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
     PROCESSOR_ARCHITECTURE: 'AMD64',
     PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel',
     PROCESSOR_LEVEL: '6',
     PROCESSOR_REVISION: '3a09',
     ProgramData: 'C:\\ProgramData',
     ProgramFiles: 'C:\\Program Files',
     'ProgramFiles(x86)': 'C:\\Program Files (x86)',
     ProgramW6432: 'C:\\Program Files',
     PROMPT: '$P$G',
     PSModulePath: 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\;E:\\devSoftware\\PowerShellModules',
     PUBLIC: 'C:\\Users\\Public',
     SESSIONNAME: 'Console',
     SVN_HOME: 'E:\\devsoft\\svnServer\\',
     SystemDrive: 'C:',
     SystemRoot: 'C:\\Windows',
     TEMP: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
     TMP: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
     USERDOMAIN: 'SD-201705071251',
     USERNAME: 'Administrator',
     USERPROFILE: 'C:\\Users\\Administrator',
     VISUALSVN_SERVER: 'E:\\devSoftware\\',
     windir: 'C:\\Windows',
     windows_tracing_flags: '3',
     windows_tracing_logfile: 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log',
     _DFX_INSTALL_UNSIGNED_DRIVER: '1' },
  pid: 5632,
  features:
   { debug: false,
     uv: true,
     ipv6: true,
     tls_npn: true,
     tls_alpn: true,
     tls_sni: true,
     tls_ocsp: true,
     tls: true },
  ppid: 4372,
  execPath: 'C:\\Program Files\\nodejs\\node.exe',
  debugPort: 9229,
  _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
  _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
  _getActiveRequests: [Function: _getActiveRequests],
  _getActiveHandles: [Function: _getActiveHandles],
  reallyExit: [Function: reallyExit],
  abort: [Function: abort],
  chdir: [Function],
  cwd: [Function],
  umask: [Function: umask],
  _kill: [Function: _kill],
  _debugProcess: [Function: _debugProcess],
  _debugPause: [Function: _debugPause],
  _debugEnd: [Function: _debugEnd],
  hrtime: [Function: hrtime],
  cpuUsage: [Function: cpuUsage],
  dlopen: [Function: dlopen],
  uptime: [Function: uptime],
  memoryUsage: [Function: memoryUsage],
  binding: [Function: binding],
  _linkedBinding: [Function: _linkedBinding],
  _setupDomainUse: [Function: _setupDomainUse],
  _events:
   { newListener: [Function],
     removeListener: [Function],
     warning: [Function],
     SIGWINCH: [ [Function], [Function] ],
     unhandledRejection: [Function],
     exit: [Function: _exit] },
  _rawDebug: [Function],
  _eventsCount: 6,
  domain: null,
  _maxListeners: undefined,
  _fatalException: [Function],
  _exiting: false,
  assert: [Function],
  config:
   { target_defaults:
      { cflags: [],
        default_configuration: 'Release',
        defines: [],
        include_dirs: [],
        libraries: [] },
     variables:
      { asan: 0,
        coverage: false,
        debug_devtools: 'node',
        debug_http2: false,
        debug_nghttp2: false,
        force_dynamic_crt: 0,
        host_arch: 'x64',
        icu_data_file: 'icudt60l.dat',
        icu_data_in: '..\\..\\deps/icu-small\\source/data/in\\icudt60l.dat',
        icu_endianness: 'l',
        icu_gyp_path: 'tools/icu/icu-generic.gyp',
        icu_locales: 'en,root',
        icu_path: 'deps/icu-small',
        icu_small: true,
        icu_ver_major: '60',
        node_byteorder: 'little',
        node_enable_d8: false,
        node_enable_v8_vtunejit: false,
        node_install_npm: true,
        node_module_version: 57,
        node_no_browser_globals: false,
        node_prefix: '/usr/local',
        node_release_urlbase: 'https://nodejs.org/download/release/',
        node_shared: false,
        node_shared_cares: false,
        node_shared_http_parser: false,
        node_shared_libuv: false,
        node_shared_nghttp2: false,
        node_shared_openssl: false,
        node_shared_zlib: false,
        node_tag: '',
        node_use_bundled_v8: true,
        node_use_dtrace: false,
        node_use_etw: true,
        node_use_lttng: false,
        node_use_openssl: true,
        node_use_perfctr: true,
        node_use_v8_platform: true,
        node_without_node_options: false,
        openssl_fips: '',
        openssl_no_asm: 0,
        shlib_suffix: 'so.57',
        target_arch: 'x64',
        v8_enable_gdbjit: 0,
        v8_enable_i18n_support: 1,
        v8_enable_inspector: 1,
        v8_no_strict_aliasing: 1,
        v8_optimized_debug: 0,
        v8_promise_internal_field_count: 1,
        v8_random_seed: 0,
        v8_trace_maps: 0,
        v8_use_snapshot: true,
        want_separate_host_toolset: 0 } },
  emitWarning: [Function],
  nextTick: [Function: nextTick],
  _tickCallback: [Function: _tickCallback],
  _tickDomainCallback: [Function: _tickDomainCallback],
  stdout: [Getter],
  stderr: [Getter],
  stdin: [Getter],
  openStdin: [Function],
  exit: [Function],
  kill: [Function],
  _immediateCallback: [Function: processImmediate],
  argv0: 'node',
  mainModule:
   {
     id: '.',
     exports: {},
     parent: null,
     filename: 'D:\\work\\react\\back-project\\scripts\\start.js',
     loaded: false,
     children:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     paths:
      [ 'D:\\work\\react\\back-project\\scripts\\node_modules',
        'D:\\work\\react\\back-project\\node_modules',
        'D:\\work\\react\\node_modules',
        'D:\\work\\node_modules',
        'D:\\node_modules' ] },
  __signal_exit_emitter__:{}
   }
